name: "Publish latest image"

on:
  push:
    branches:
      - "master"

permissions:
  contents: "read"
  packages: "write"

env:
  REGISTRY: "ghcr.io"

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up variables"
        run: |
          echo IMAGE_NAME=$(echo "$GITHUB_REPOSITORY" | tr "[:upper:]" "[:lower:]") >> $GITHUB_ENV
          echo SHA_SHORT=$(echo "$GITHUB_SHA" | head -c7) >> $GITHUB_ENV

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v3"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Log in to the Container registry"
        uses: "docker/login-action@v3"
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push"
        uses: "docker/build-push-action@v5"
        with:
          context: "."
          build-args: |
            APP_VERSION=${{ env.SHA_SHORT }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHA_SHORT }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          push: true
